Repository opendatahub-io/kserve, pull requests merged in 2023-10, with the labels that each got.

#97 automate addition of new isues into ODH board
  .github/workflows/auto-add-issues-to-project.yaml
Labels: approved, lgtm

#93 [v0.11] Changes to minimize exposure to security issues
  cmd/agent/main.go
  python/kserve/poetry.lock
  test/scripts/openshift-ci/deploy.serverless.sh
Labels: approved, lgtm

#94 [v0.11] Changes to minimize exposure to security issues
  cmd/agent/main.go
  python/kserve/poetry.lock
  test/scripts/openshift-ci/deploy.serverless.sh
Labels: approved

#100 cherry-pick fix-3171
  python/kserve/kserve/storage/storage.py
Labels: approved, lgtm, rhods-1.34

#107 Preparation for odh-opeartor v2
  config/overlays/odh/inferenceservice-config-patch.yaml
  config/overlays/odh/kustomization.yaml
  config/overlays/odh/params.env
  config/overlays/odh/params.yaml
  python/storage-initializer.Dockerfile
Labels: approved, lgtm

#110 add spoltin in the OWNERS file
  OWNERS
Labels: approved, lgtm

#109 [RHODS-12555] - CVE-2023-44487
  go.mod
  go.sum
Labels: approved, lgtm

#114 [RHODS-12555] - CVE-2023-44487 - qpext
  qpext/go.mod
  qpext/go.sum
Labels: approved, lgtm

#111 [master] Preparation for odh-opeartor v2
  config/overlays/odh/inferenceservice-config-patch.yaml
  config/overlays/odh/kustomization.yaml
  config/overlays/odh/params.env
  config/overlays/odh/params.yaml
  test/scripts/openshift-ci/deploy.serverless.sh
Labels: approved, lgtm

#116 [RHODS-12555] - CVE-2023-44487 - qpext
  qpext/go.mod
  qpext/go.sum
Labels: approved, lgtm

#115 Enable Istio Virtual Host
  config/overlays/odh/inferenceservice-config-patch.yaml
Labels: approved, lgtm
