Repository opendatahub-io/kserve, pull requests merged in 2024-04, with the labels that each got.

#288 [RHOAIENG-5073] - Routing and Headless Service Support in KServe Raw Mode Deployment
  Makefile
  pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go
  test/e2e/logger/test_logger.py
  test/e2e/logger/test_raw_logger.py
Labels: approved, lgtm

#262 Prepare ODH's v0.12.0 branch cut
  python/kserve/kserve/protocol/infer_type.py
  python/kserve/test/test_infer_type.py
Labels: approved, lgtm

#295 [RHOAIENG-5305] - golang.org/x/net Allocation of Resources Without Limits or Throttling
  go.mod
  go.sum
Labels: approved, lgtm

#297 [RHOAIENG-5335] [custom_model|trasformer] pillow - Buffer Overflow
  python/aiffairness/poetry.lock
  python/alibiexplainer/poetry.lock
  python/alibiexplainer/pyproject.toml
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_model/pyproject.toml
  python/custom_transformer/poetry.lock
  python/custom_transformer/pyproject.toml
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/pmmlserver/poetry.lock
  python/sklearnserver/poetry.lock
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/xgbserver/poetry.lock
Labels: approved

#314 [RHOAIENG-5231] - cloudevents/sdk-go Information Exposure Through Sent Data
  go.mod
  go.sum
  pkg/logger/handler.go
  pkg/logger/types.go
  pkg/logger/worker.go
Labels: approved

#313 [RHOAIENG-5305] - golang.org/x/net Allocation of Resources Without Li…
  qpext/go.mod
  qpext/go.sum
Labels: approved

#291 Go vulnerability fixes (#3442)
  go.sum
  qpext/go.mod
  qpext/go.sum
Labels: approved

#317 remove unnecessary operators for e2e
  test/scripts/openshift-ci/deploy.ossm.sh
Labels: approved, lgtm

#318 remove unnecessary operators
  test/scripts/openshift-ci/deploy.ossm.sh
Labels: approved, lgtm

#287 Create Workflow for release and tag with Changelog
  .github/workflows/create-release-tag.yml
  .github/workflows/odh-create-release-tag.yml
Labels: approved, lgtm, ok-to-test

#336 remove domain-mapping waiting for e2e ci
  test/scripts/openshift-ci/deploy.serverless.sh
Labels: approved

#337 remove domain-mapping waiting for e2e ci and update smcp to fix ci
  test/scripts/openshift-ci/deploy.ossm.sh
  test/scripts/openshift-ci/deploy.serverless.sh
Labels: approved

#316 remove unnecessary operators
  test/scripts/openshift-ci/deploy.ossm.sh
Labels: approved, lgtm

#338 [v0.11.1] Allow disabling creation of the HPA in raw deployment mode (#3086)
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go
Labels: approved

#292 [RHOAIENG-4617] - follow up - remove hardcoded fastapi from Dockerfile
  python/storage-initializer.Dockerfile
Labels: approved, lgtm
