Repository opendatahub-io/kserve, pull requests merged in 2024-08, with the labels that each got.

#395 explicitly enable ubi-8 baseos repo
  Dockerfile
  agent.Dockerfile
  python/storage-initializer.Dockerfile
  router.Dockerfile
Labels: approved, lgtm

#391 Removed arm/v7 to make the jobs working again for now
  .github/workflows/agent-docker-publish.yml
  .github/workflows/kserve-controller-docker-publish.yml
  .github/workflows/qpext-docker-publish.yml
  .github/workflows/router-docker-publish.yml
Labels: approved, lgtm, needs-ok-to-test

#397 [release-v0.12.1] Removed arm/v7 to make the jobs working again for now
  .github/workflows/agent-docker-publish.yml
  .github/workflows/kserve-controller-docker-publish.yml
  .github/workflows/qpext-docker-publish.yml
  .github/workflows/router-docker-publish.yml
Labels: approved, lgtm

#398 [release-v0.12.1] inferenceservice controller: fix error check in Serverless mode
  pkg/controller/v1beta1/inferenceservice/controller.go
Labels: approved, lgtm

#396 [RHOAIENG-10904] Updated istio versions based on go version 1.21
  go.mod
  go.sum
Labels: approved, lgtm

#401 Fix apiGroups in aggregate roles on manifests
  config/overlays/odh/user-cluster-roles.yaml
Labels: approved

#402 Fix apiGroups in aggregate roles on manifests
  config/overlays/odh/user-cluster-roles.yaml
Labels: approved, lgtm
