Repository opendatahub-io/kserve, pull requests merged in 2025-07, with the labels that each got.

#719 feat(router): resolves model URLs
  pkg/controller/llmisvc/DEV.md
  pkg/controller/llmisvc/controller_test.go
  pkg/controller/llmisvc/fixture/gwapi_builders.go
  pkg/controller/llmisvc/fixture/required_resources.go
  pkg/controller/llmisvc/router.go
  pkg/controller/llmisvc/router_discovery.go
  pkg/controller/llmisvc/router_discovery_filter.go
  pkg/controller/llmisvc/router_discovery_test.go
Labels: lgtm

#716 Support LWS-based multi node with data parallelism of MoE models
  charts/kserve-resources/templates/clusterrole.yaml
  config/crd/full/serving.kserve.io_llminferenceserviceconfigs.yaml
  config/crd/full/serving.kserve.io_llminferenceservices.yaml
  config/llmisvc/config-llm-decode-template-gpu-small.yaml
  config/llmisvc/config-llm-decode-template.yaml
  config/llmisvc/config-llm-decode-worker-data-parallel.yaml
  config/llmisvc/config-llm-prefill-template-gpu-small.yaml
  config/llmisvc/config-llm-prefill-template.yaml
  config/llmisvc/config-llm-prefill-worker-data-parallel.yaml
  config/llmisvc/config-llm-scheduler.yaml
  config/llmisvc/config-llm-template.yaml
  config/llmisvc/config-llm-worker-data-parallel.yaml
  config/llmisvc/kustomization.yaml
  config/rbac/role.yaml
  docs/samples/llmisvc/opt-125m/llm-inference-service-facebook-opt-125m-cpu.yaml
  docs/samples/llmisvc/opt-125m/llm-inference-service-pd-facebook-opt-125m-cpu.yaml
  go.mod
  go.sum
  hack/deploy_dev_llm.sh
  pkg/apis/serving/v1alpha1/llm_inference_service_lifecycle.go
  pkg/apis/serving/v1alpha1/llm_inference_service_types.go
  pkg/apis/serving/v1alpha1/llm_inference_service_types_func.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/llmisvc/config_merge.go
  pkg/controller/llmisvc/config_merge_test.go
  pkg/controller/llmisvc/config_presets_test.go
  pkg/controller/llmisvc/controller.go
  pkg/controller/llmisvc/lifecycle_crud.go
  pkg/controller/llmisvc/router.go
  pkg/controller/llmisvc/scheduler.go
  pkg/controller/llmisvc/workload.go
  pkg/controller/llmisvc/workload_multi_node.go
  pkg/controller/llmisvc/workload_prefill.go
  pkg/controller/llmisvc/workload_single_node.go
  test/crds/leaderworkerset.x-k8s.io_leaderworkersets.yaml
  test/crds/serving.kserve.io_all_crds.yaml
  test/scripts/gh-actions/setup-deps.sh
Labels: lgtm

#720 [WIP] Fix typo in LLMD developer documentation
  pkg/controller/llmisvc/DEV.md
Labels: approved, do-not-merge/work-in-progress

#709 Restore zero initial scale behavior on master branch
  charts/kserve-resources/templates/clusterrole.yaml
  cmd/manager/main.go
  config/configmap/inferenceservice.yaml
  config/overlays/odh/inferenceservice-config-patch.yaml
  config/overlays/test/configmap/inferenceservice-openshift-ci-serverless-predictor.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/controller/v1alpha1/inferencegraph/controller.go
  pkg/controller/v1alpha1/inferencegraph/controller_test.go
  pkg/controller/v1alpha1/utils/utils.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/testing/envtest_setup.go
  test/crds/knative_knativeserving.yaml
Labels: approved, lgtm

#721 chore(presets): simplifies template defaulting
  config/llmisvc/config-llm-decode-worker-data-parallel.yaml
  config/llmisvc/config-llm-prefill-worker-data-parallel.yaml
  config/llmisvc/config-llm-worker-data-parallel.yaml
  pkg/controller/llmisvc/config_merge.go
Labels: approved, lgtm

#724 chore: moves sample LLMInferenceService to its own func
  pkg/controller/llmisvc/config_presets_test.go
  pkg/controller/llmisvc/sample.go
Labels: approved, lgtm

#725 chore(kustomize): consolidates webhook patching
  config/default/kustomization.yaml
Labels: lgtm

#728 Add instructions for dev setup of LLMIsvc on minikube
  pkg/controller/llmisvc/DEV.md
Labels: lgtm

#714 Improve Model Load Status Check in s3-TLS FVT Tests
  test/e2e/storagespec/test_s3_tls_storagespec.py
Labels: approved, lgtm

#722 update istio experimental image
  test/overlays/llm-istio-experimental/istio_base.yaml
  test/overlays/llm-istio-experimental/istiod.yaml
  test/scripts/gh-actions/setup-deps.sh
Labels: approved, lgtm

#733 chore: follow-up to #729
  pkg/controller/llmisvc/scheduler.go
Labels: lgtm, llm-d

#734 chore: remaining Reconcile re-use
  pkg/controller/llmisvc/lifecycle_crud.go
  pkg/controller/llmisvc/scheduler.go
Labels: lgtm, llm-d

#730 feat(storage): add PVC support for model storage to LLMIsvc
  config/llmisvc/config-llm-template.yaml
  docs/samples/llmisvc/opt-125m/llm-inference-service-facebook-opt-125m-cpu.yaml
  pkg/constants/constants.go
  pkg/controller/llmisvc/controller_test.go
  pkg/controller/llmisvc/workload_single_node.go
  pkg/utils/storage.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
  test/overlays/llm-istio-experimental/istiod.yaml
Labels: lgtm, llm-d

#735 chore: adds unit tests for webhook warnings
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/fixture/required_resources.go
  pkg/controller/llmisvc/webhook/config_validation_test.go
  pkg/controller/llmisvc/webhook/config_validator.go
  pkg/controller/llmisvc/webhook/webhook_int_test.go
Labels: llm-d

#745 fix(reconcile): populates routing status for user-def routes
  pkg/apis/serving/v1alpha1/llm_inference_service_types_func.go
  pkg/controller/llmisvc/router.go
Labels: lgtm

#746 Improve enqueue logic for Gateway and well-known presets
  pkg/controller/llmisvc/controller.go
Labels: lgtm

#749 Configure scheduler to FailOpen and fallback to random loadbalancing
  config/llmisvc/config-llm-scheduler.yaml
Labels: lgtm

#738 feat(storage): add OCI storage support via modelcars
  pkg/apis/serving/v1beta1/configmap.go
  pkg/constants/constants.go
  pkg/controller/llmisvc/controller.go
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/fixture/required_resources.go
  pkg/controller/llmisvc/suite_test.go
  pkg/controller/llmisvc/workload.go
  pkg/controller/llmisvc/workload_single_node.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/cabundleconfigmap/cabundle_configmap_reconciler.go
  pkg/types/config.go
  pkg/utils/storage.go
  pkg/utils/utils.go
  pkg/webhook/admission/pod/mutator.go
  pkg/webhook/admission/pod/mutator_test.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: lgtm

#753 fix(test): uses local httptest server urls for downloader tests
  pkg/agent/watcher_test.go
Labels: approved, lgtm

#754 feat(webhook): ensures proper paralellism settings
  pkg/controller/llmisvc/fixture/llmisvc_builders.go
  pkg/controller/llmisvc/webhook/llminferenceservice_validator.go
  pkg/controller/llmisvc/webhook/llminferenceservice_validator_int_test.go
Labels: approved, lgtm, llm-d

#756 Updating s3 tls fvt tests to cover all new scenarios
  test/e2e/storagespec/test_s3_tls_storagespec.py
  test/scripts/openshift-ci/teardown-e2e-setup.sh
Labels: approved, lgtm

#742 Support TLS with self-signed certificates for LLMInferenceService
  charts/kserve-resources/templates/clusterrole.yaml
  config/llmisvc/config-llm-decode-template.yaml
  config/llmisvc/config-llm-decode-worker-data-parallel.yaml
  config/llmisvc/config-llm-prefill-template.yaml
  config/llmisvc/config-llm-prefill-worker-data-parallel.yaml
  config/llmisvc/config-llm-scheduler.yaml
  config/llmisvc/config-llm-template.yaml
  config/llmisvc/config-llm-worker-data-parallel.yaml
  config/rbac/role.yaml
  docs/samples/llmisvc/opt-125m/llm-inference-service-pd-facebook-opt-125m-cpu.yaml
  go.mod
  pkg/apis/serving/v1alpha1/llm_inference_service_types_func.go
  pkg/controller/llmisvc/DEV.md
  pkg/controller/llmisvc/config_merge.go
  pkg/controller/llmisvc/config_presets_test.go
  pkg/controller/llmisvc/controller.go
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/fixture/gwapi_builders.go
  pkg/controller/llmisvc/fixture/required_resources.go
  pkg/controller/llmisvc/lifecycle_crud.go
  pkg/controller/llmisvc/router.go
  pkg/controller/llmisvc/router_discovery.go
  pkg/controller/llmisvc/router_discovery_filter.go
  pkg/controller/llmisvc/router_discovery_test.go
  pkg/controller/llmisvc/scheduler.go
  pkg/controller/llmisvc/workload.go
  pkg/controller/llmisvc/workload_multi_node.go
  pkg/controller/llmisvc/workload_single_node.go
  pkg/controller/llmisvc/workload_tls_self_signed.go
  pkg/controller/llmisvc/workload_tls_self_signed_istio.go
  test/crds/gatewayapi_gatewayclasses.yaml
  test/crds/istio.yaml
  test/crds/istio_virtualservice.yaml
Labels: approved, lgtm

#758 fix(test): adds required storage initializer settings to test configmap
  config/overlays/test/configmap/inferenceservice.yaml
Labels: approved, lgtm, llm-d

#748 RHOAIENG-30217: Enable SSRF protection for sidecar
  config/llmisvc/config-llm-decode-template.yaml
  config/llmisvc/config-llm-decode-worker-data-parallel.yaml
  pkg/controller/llmisvc/config_presets_test.go
  pkg/controller/llmisvc/workload.go
  pkg/controller/llmisvc/workload_multi_node.go
  pkg/controller/llmisvc/workload_single_node.go
Labels: approved, lgtm, jira/valid-reference

#762 fix(deps): adds missing LLMInferenceService types for python
  python/kserve/kserve/__init__.py
Labels: approved, lgtm

#764 feat(ci): adds status check for system namespace
  test/scripts/gh-actions/status-check.sh
Labels: approved, lgtm, llm-d

#761 RHOAIENG-30166: Upgrade to llm-d 0.2
  config/llmisvc/config-llm-decode-template.yaml
  config/llmisvc/config-llm-decode-worker-data-parallel.yaml
  config/llmisvc/config-llm-prefill-template.yaml
  config/llmisvc/config-llm-prefill-worker-data-parallel.yaml
  config/llmisvc/config-llm-scheduler.yaml
  config/llmisvc/config-llm-template.yaml
  config/llmisvc/config-llm-worker-data-parallel.yaml
  pkg/controller/llmisvc/DEV.md
  pkg/controller/llmisvc/config_merge.go
  pkg/controller/llmisvc/config_presets_test.go
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/sample.go
  pkg/controller/llmisvc/scheduler.go
  pkg/controller/llmisvc/workload_single_node.go
  pkg/controller/llmisvc/workload_tls_self_signed.go
  test/scripts/gh-actions/setup-deps.sh
Labels: approved, lgtm, jira/valid-reference

#770 RHOAIENG-30193-fixed-constant-looping cherry pick
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
Labels: approved, lgtm

#772 fix(presets): respects baseRefs defaults
  pkg/controller/llmisvc/config_merge.go
  pkg/controller/llmisvc/config_merge_test.go
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/fixture/llmisvc_builders.go
Labels: approved, lgtm, llm-d

#777 add llmd scheduler/routing sidecar image to params.env
  config/overlays/odh/config-llm-decode-template-patch.yaml
  config/overlays/odh/config-llm-decode-worker-data-parallel-patch.yaml
  config/overlays/odh/config-llm-scheduler-patch.yaml
  config/overlays/odh/kustomization.yaml
  config/overlays/odh/params.env
  config/overlays/odh/params.yaml
Labels: approved

#781 update istiod yaml file to increase resources
  test/overlays/llm-istio-experimental/istiod.yaml
Labels: approved, lgtm

#778 add GIE CRD
  config/crd/external/gie/kustomization.yaml
  config/overlays/odh/kustomization.yaml
Labels: approved, lgtm

#784 fix: fixes misleading print for parallelism when $# > 2
  test/scripts/gh-actions/run-e2e-tests.sh
Labels: approved, lgtm

#783 chore: updates router sidecar image
  docs/samples/llmisvc/opt-125m/llm-inference-service-pd-facebook-opt-125m-cpu.yaml
Labels: approved, lgtm, llm-d

#786 Prefetch GIE CRDs
  Makefile
  config/llmisvc/gie.yaml
  config/llmisvc/kustomization.yaml
  config/overlays/odh/kustomization.yaml
Labels: approved, lgtm

#785 fix: defaults GITHUB_SHA for graph images
  test/e2e/graph/test_inference_graph.py
Labels: approved, lgtm

#790 chore: simplifies url filtering
  pkg/controller/llmisvc/router_discovery_filter.go
Labels: approved, lgtm

#782 feat: Enable LLM disaggregated serving on OpenShift
  config/default/kustomization.yaml
  config/overlays/odh/config-llm-decode-template-patch.yaml
  config/overlays/odh/config-llm-decode-worker-data-parallel-patch.yaml
  config/overlays/odh/config-llm-scheduler-patch.yaml
  config/overlays/odh/inferenceservice-config-patch.yaml
  config/overlays/odh/kustomization.yaml
  pkg/controller/llmisvc/DEV.md
Labels: approved

#780 fix: add HuggingFace environment variable(HF_HOME) for storage-initializer
  pkg/utils/storage.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: approved, lgtm

#774 test(e2e): introduces e2e test skeleton
  .flake8
  .github/actions/kserve-dep-setup/action.yml
  .github/actions/minikube-setup/action.yml
  .github/workflows/e2e-test-llmisvc.yml
  Makefile
  pkg/controller/llmisvc/DEV.md
  test/e2e/llmisvc/README.md
  test/e2e/llmisvc/__init__.py
  test/e2e/llmisvc/conftest.py
  test/e2e/llmisvc/diagnostic.py
  test/e2e/llmisvc/fixtures.py
  test/e2e/llmisvc/logging.py
  test/e2e/llmisvc/test_llm_inference_service.py
  test/e2e/pytest.ini
Labels: approved, lgtm, llm-d

#799 docs: minor fixes in DEV.md
  pkg/controller/llmisvc/DEV.md
Labels: approved, lgtm, llm-d

#796 docs: removes obsolote note about errors
  pkg/controller/llmisvc/DEV.md
Labels: approved, lgtm, llm-d

#760 fix(scheduler): Uses ClusterRole for TokenReview and SAR resources
  charts/kserve-resources/templates/clusterrole.yaml
  config/rbac/role.yaml
  pkg/controller/llmisvc/controller.go
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/lifecycle_crud.go
  pkg/controller/llmisvc/scheduler.go
Labels: approved, lgtm, llm-d

#793 add prebuilt OSSM installation guide
  pkg/controller/llmisvc/DEV.md
Labels: approved, lgtm, llm-d

#804 remove uidModelcar value from inferenceservice-config configmap inodh
  config/overlays/odh/inferenceservice-config-patch.yaml
  config/overlays/test/configmap/inferenceservice-openshift-ci-serverless-predictor.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  pkg/controller/llmisvc/fixture/required_resources.go
Labels: approved, lgtm
