Repository opendatahub-io/kserve, pull requests merged in 2025-05, with the labels that each got.

#580 fix indent bug in e2e raw setup
  config/overlays/test/configmap/inferenceservice-openshift-ci-raw.yaml
Labels: approved, lgtm

#582 Add optional go1.22 image and profile to utilize it
  dev_tools/README.md
  dev_tools/devspace.yaml
Labels: approved, lgtm

#573 Fix e2e graph tests script
  config/overlays/test/configmap/inferenceservice-openshift-ci-serverless-predictor.yaml
  docs/odh/fvt-tests.md
  test/scripts/openshift-ci/README.md
  test/scripts/openshift-ci/deploy.ossm.sh
  test/scripts/openshift-ci/deploy.serverless.sh
  test/scripts/openshift-ci/run-e2e-tests.sh
  test/scripts/openshift-ci/setup-e2e-tests.sh
Labels: approved, lgtm

#609 [RHOAIENG-22171] Added option to build and push kserve images.
  test/scripts/openshift-ci/build-kserve-images.sh
  test/scripts/openshift-ci/run-e2e-tests.sh
Labels: approved, lgtm

#581 Fix Raw InferenceGraph not connecting to ISVCs
  pkg/controller/v1alpha1/inferencegraph/raw_ig.go
  pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go
Labels: approved, lgtm

#618 Allow OCI for multi-node/multi-gpu
  config/runtimes/kserve-huggingfaceserver-multinode.yaml
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/apis/serving/v1beta1/inference_service_validation_test.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: approved, lgtm

#620 Allow OCI for multi-node/multi-gpu [v0.15]
  config/runtimes/kserve-huggingfaceserver-multinode.yaml
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/apis/serving/v1beta1/inference_service_validation_test.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: approved, lgtm

#615 Add guide to create a new branch from an upstream release
  CONTRIBUTING.md
  docs/odh/fetch-upstream-release.md
Labels: approved

#637 Disallow Propagation of haproxy.router.openshift.io/timeout Annotation
  config/overlays/odh/inferenceservice-config-patch.yaml
  config/overlays/test/configmap/inferenceservice-openshift-ci-serverless-predictor.yaml
Labels: approved, lgtm

#642 Revert "RHOAIENG-25750: Split syncable and static params"
  config/overlays/odh/kustomization.yaml
  config/overlays/odh/params-synced.env
  config/overlays/odh/params.env
Labels: approved, lgtm, jira/valid-reference
