Repository opendatahub-io/kserve, pull requests merged in 2025-06, with the labels that each got.

#649 Fix references to ODH images in params.env
  config/overlays/odh/params.env
Labels: approved, lgtm

#646 Restoring zero initial scale behavior
  charts/kserve-resources/templates/clusterrole.yaml
  cmd/manager/main.go
  config/configmap/inferenceservice.yaml
  config/overlays/odh/inferenceservice-config-patch.yaml
  config/overlays/test/configmap/inferenceservice-openshift-ci-serverless-predictor.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/controller/v1alpha1/inferencegraph/controller.go
  pkg/controller/v1alpha1/inferencegraph/controller_test.go
  pkg/controller/v1alpha1/inferencegraph/suite_test.go
  pkg/controller/v1alpha1/utils/utils.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/suite_test.go
  pkg/testing/envtest_setup.go
  test/crds/knative_knativeserving.yaml
Labels: approved, lgtm

#659 [Cherry pick] Python test fixes from upstream
  python/huggingface_server_cpu.Dockerfile
  python/huggingfaceserver/Makefile
  python/huggingfaceserver/huggingfaceserver/request_logger.py
Labels: approved, lgtm

#660 [Cherry pick] Python test fixes from upstream
  python/huggingface_server_cpu.Dockerfile
  python/huggingfaceserver/Makefile
  python/huggingfaceserver/huggingfaceserver/request_logger.py
Labels: approved, lgtm

#658 [Cherry pick] Stop and resume a model [Raw Deployment] (#4455)
  pkg/apis/serving/v1beta1/inference_service.go
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/httproute_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/keda/keda_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/otel/otel_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go
  pkg/utils/utils.go
Labels: approved, lgtm

#657 [RHOAIENG-26152] created-fvt-test-for-knative-feature-schedulername
  docs/odh/fvt-tests.md
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  test/e2e/predictor/test_scheduler_name.py
  test/scripts/openshift-ci/deploy.serverless.sh
Labels: approved, lgtm

#661 [Cherry pick][Release 0.15] Stop and resume a model [Raw Deployment]
  pkg/apis/serving/v1beta1/inference_service.go
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/httproute_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/keda/keda_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/otel/otel_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go
  pkg/utils/utils.go
Labels: approved, lgtm

#663 [Cherry pick v0.14] Stop and resume a model by adding a new annotation
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go
  pkg/utils/utils.go
Labels: approved, lgtm

#668 [RHOAIENG-26924] - CVE-2025-43859: h11 HTTP Request Smuggling
  docs/samples/explanation/alibi/alibiexplainer/poetry.lock
  docs/samples/explanation/alibi/alibiexplainer/pyproject.toml
  python/aiffairness/poetry.lock
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_tokenizer/poetry.lock
  python/custom_transformer/poetry.lock
  python/huggingfaceserver/poetry.lock
  python/kserve/poetry.lock
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/pmmlserver/poetry.lock
  python/sklearnserver/poetry.lock
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/xgbserver/poetry.lock
Labels: approved, lgtm

#669 [Cherry Pick] Ignore Openshift Route Timeout Annotation
  config/overlays/odh/inferenceservice-config-patch.yaml
  config/overlays/test/configmap/inferenceservice-openshift-ci-serverless-predictor.yaml
Labels: approved, lgtm

#670 [RHOAIENG-27166] Fix flaky test failure with mc alias
  test/scripts/openshift-ci/setup-e2e-tests.sh
  test/scripts/openshift-ci/tls/setup-minio-tls-custom-cert.sh
  test/scripts/openshift-ci/tls/setup-minio-tls-serving-cert.sh
Labels: approved, lgtm

#675 feat: improves status and events handling
  pkg/controller/llmisvc/controller.go
  pkg/openapi/openapi_generated.go
Labels: lgtm

#678 Resolve Resource Conflict In FVT Tests
  test/e2e/predictor/test_scheduler_name.py
Labels: approved, lgtm

#684 [RHOAIENG-28024] update pip version
  python/storage-initializer.Dockerfile
Labels: approved, lgtm

#677 Docs on how to get a token for protected InferenceServices
  docs/odh/authorization.md
Labels: approved, lgtm

#689 Sync/250623 upstream master
  SECURITY.md
  charts/kserve-resources/README.md
  charts/kserve-resources/values.yaml
  config/configmap/inferenceservice.yaml
  pkg/constants/constants.go
  pkg/controller/v1alpha1/inferencegraph/controller.go
  pkg/controller/v1alpha1/inferencegraph/controller_test.go
  pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go
  pkg/controller/v1alpha1/utils/utils.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler_test.go
  python/kserve/kserve/model_server.py
  test/e2e/common/utils.py
  test/e2e/data/opt_125m_completion_input.json
  test/e2e/data/opt_125m_input_generate.json
  test/e2e/data/qwen_input_chat.json
  test/e2e/data/qwen_input_chat_stream.json
  test/e2e/data/qwen_input_cmpl.json
  test/e2e/data/qwen_input_cmpl_stream.json
  test/e2e/modelcache/test_localmodelcache.py
  test/e2e/predictor/test_huggingface.py
  test/e2e/predictor/test_huggingface_vllm_cpu.py
Labels: approved, lgtm, tide/merge-method-merge

#698 test: ensures presets are valid
  pkg/controller/llmisvc/config_merge_test.go
  pkg/controller/llmisvc/config_presets_test.go
Labels: approved, lgtm

#699 follow up deployment script for llmd
  Makefile
  hack/deploy_dev_llm.sh
Labels: approved, lgtm

#703 [Cherry-pick] Stop and Resume a transformer
  Makefile
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/httproute_reconciler.go
Labels: approved, lgtm

#704 [Cherry-pick] Stop and Resume a transformer
  Makefile
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/httproute_reconciler.go
Labels: approved, lgtm

#619 fix keda raw e2e tests for odh
  python/kserve/test/test_v1beta1_external_metrics.py
  python/kserve/test/test_v1beta1_oauth_config.py
  python/kserve/test/test_v1beta1_pod_metrics.py
  test/e2e/predictor/test_autoscaling.py
  test/e2e/transformer/test_collocation.py
  test/scripts/openshift-ci/setup-e2e-tests.sh
Labels: approved, lgtm

#650 [RHOAIENG-15553] Adding the kfp template to the odh/kfp docs.
  .pre-commit-config.yaml
  docs/kfp/template/README.md
  docs/kfp/template/cli.py
  docs/kfp/template/component.yaml
  docs/kfp/template/deploy_utils.py
  docs/kfp/template/env_utils.py
  docs/kfp/template/kservedeployer.py
  docs/kfp/template/main.py
  docs/kfp/template/manifests/dspa.yaml
  docs/kfp/template/manifests/kustomization.yaml
  docs/kfp/template/manifests/role-binding.yaml
  docs/kfp/template/manifests/role.yaml
  docs/kfp/template/manifests/runtime.yaml
  docs/kfp/template/pipeline/delete_model_pipeline.py
  docs/kfp/template/pipeline/deploy_model_pipeline.py
  docs/kfp/template/requirements.in
Labels: approved, lgtm

#707 Fix panic for invalid templates and add additional tests for MergeSpecs and ReplaceVariables
  pkg/controller/llmisvc/config_merge.go
  pkg/controller/llmisvc/config_merge_test.go
Labels: lgtm

#706 Stop and resume an explainer
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/httproute_reconciler.go
Labels: approved, lgtm

#705 [Cherry pick] Stop and resume an explainer
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/httproute_reconciler.go
Labels: approved, lgtm
