Repository opendatahub-io/kserve, pull requests merged in 2025-08, with the labels that each got.

#811 update gatewayclass controller name
  pkg/controller/llmisvc/controller.go
Labels: approved, lgtm

#812 Add a guide how to use OSSM by OCP
  pkg/controller/llmisvc/DEV.md
Labels: approved

#807 feat(storage): add storage configuration support to llmisvc prefill workloads
  config/llmisvc/config-llm-prefill-template.yaml
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/controller_workload_storage_int_test.go
  pkg/controller/llmisvc/workload_single_node.go
Labels: approved, lgtm, llm-d

#809 feat: disallows BaseRefs field in LLMInferenceServiceConfig
  pkg/controller/llmisvc/webhook/config_validator.go
  pkg/controller/llmisvc/webhook/config_validator_int_test.go
Labels: approved, lgtm, llm-d

#822 [Cherry pick] [Followup] Improve the stop/resume Inference Service tests and status…
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
Labels: approved, lgtm

#823 update dev.md to use official OSSM 3.1
  pkg/controller/llmisvc/DEV.md
Labels: approved, lgtm, llm-d

#826 Fix llmisvc PodMonitor portNumber -> targetPort
  config/monitoring/llmisvc/engine_vllm_monitor.yaml
Labels: approved, lgtm

#824 chore: moves config logic to its own file
  pkg/controller/llmisvc/config_loader.go
  pkg/controller/llmisvc/controller.go
Labels: approved, lgtm, llm-d

#816 [RHOAIENG-31248] - KServe http: TLS handshake error from XXXXXX: remo…
  config/default/localmodelcache_validatingwebhook_cainjection_patch.yaml
  config/webhook/manifests.yaml
Labels: approved, lgtm

#828 align deploy command logic in makefile
  Makefile
Labels: approved, lgtm

#829 fix(router): brings back destination rules reconcile
  pkg/controller/llmisvc/router.go
Labels: approved, lgtm

#818 Apply Authentication for LLMISVC on OpenShift
  pkg/controller/llmisvc/DEV-authz.md
Labels: approved

#838 chore(ci): bumps default ginkgo timeout to 30s
  pkg/controller/llmisvc/fixture/envtest.go
Labels: approved, lgtm, llm-d

#831 chore: simplifies external CRD fetching
  Makefile
  config/crd/external/gateway-inference-extension/gateway-inference-extension.yaml
  config/crd/external/gateway-inference-extension/kustomization.yaml
  config/crd/external/gie/kustomization.yaml
  config/crd/external/opendatahub-operator/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/external/opendatahub-operator/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/external/opendatahub-operator/kustomization.yaml
  config/llmisvc/kustomization.yaml
  config/overlays/test/kustomization.yaml
  test/scripts/openshift-ci/setup-e2e-tests.sh
Labels: approved, llm-d

#833 feat(e2e): installs llm-d specific infra stack
  config/overlays/test/configmap/inferenceservice-openshift-ci-llm.yaml
  test/scripts/openshift-ci/common.sh
  test/scripts/openshift-ci/infra/deploy.cert-manager.sh
  test/scripts/openshift-ci/infra/deploy.cma.sh
  test/scripts/openshift-ci/infra/deploy.istio-exp.sh
  test/scripts/openshift-ci/infra/deploy.lws.sh
  test/scripts/openshift-ci/infra/deploy.ossm.sh
  test/scripts/openshift-ci/infra/deploy.serverless.sh
  test/scripts/openshift-ci/run-e2e-tests.sh
  test/scripts/openshift-ci/setup-e2e-tests.sh
  test/scripts/openshift-ci/teardown-e2e-setup.sh
Labels: approved, llm-d

#815 refactor: uses kustomize overlays for separation of concerns
  config/crd/full/kustomization.yaml
  config/crd/kustomization.yaml
  config/crd/minimal/kustomization.yaml
  config/default/cainjection_conversion_webhook.yaml
  config/default/inferencegraph_validatingwebhook_cainjection_patch.yaml
  config/default/isvc_mutatingwebhook_cainjection_patch.yaml
  config/default/isvc_validatingwebhook_cainjection_patch.yaml
  config/default/kustomization.yaml
  config/default/localmodelcache_validatingwebhook_cainjection_patch.yaml
  config/default/servingruntime_validationwebhook_cainjection_patch.yaml
  config/default/trainedmodel_validatingwebhook_cainjection_patch.yaml
  config/overlays/odh-test/clusterresources/kustomization.yaml
  config/overlays/odh-test/configmap/inferenceservice-openshift-ci-llm.yaml
  config/overlays/odh-test/configmap/inferenceservice-openshift-ci-raw.yaml
  config/overlays/odh-test/configmap/inferenceservice-openshift-ci-serverless-predictor.yaml
  config/overlays/odh-test/configmap/inferenceservice-openshift-ci-serverless.yaml
  config/overlays/odh-test/dsc.yaml
  config/overlays/odh-test/dsci.yaml
  config/overlays/odh-test/kustomization.yaml
  config/overlays/odh-test/manager_image_patch.yaml
  config/overlays/odh/kustomization.yaml
  config/overlays/odh/network-policies.yaml
  config/overlays/odh/patches/patch-inferenceservice-config.yaml
  config/overlays/odh/patches/patch-set-resources-manager.yaml
  config/overlays/odh/patches/patch-webhook-svc-openshift-cert-injection.yaml
  config/overlays/odh/patches/remove-cert-manager.yaml
  config/overlays/odh/patches/remove-clusterservingruntime.yaml
  config/overlays/odh/patches/remove-local-model.yaml
  config/overlays/odh/remove-namespace.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  config/overlays/test/kustomization.yaml
  config/runtimes/kserve-tensorflow-serving.yaml
  config/runtimes/kserve-torchserve.yaml
  config/runtimes/kserve-tritonserver.yaml
  config/webhook/manifests.yaml
  test/crds/serving.kserve.io_all_crds.yaml
  test/scripts/openshift-ci/kustomization.yaml
  test/scripts/openshift-ci/run-e2e-tests.sh
  test/scripts/openshift-ci/setup-e2e-tests.sh
  test/scripts/openshift-ci/teardown-e2e-setup.sh
Labels: approved, lgtm, llm-d

#839 Allow using HTTPRoute without scheduler and external InferencePool Ref
  docs/samples/llmisvc/opt-125m/llm-inference-service-facebook-opt-125m-cpu-no-scheduler.yaml
  pkg/controller/llmisvc/config_merge.go
  pkg/controller/llmisvc/controller.go
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/fixture/gwapi_builders.go
  pkg/controller/llmisvc/router.go
  pkg/controller/llmisvc/scheduler.go
  pkg/controller/llmisvc/workload.go
  pkg/testing/httproute_matchers.go
Labels: approved, lgtm, llm-d

#852 chore: renames controlled-by owner assertion
  pkg/controller/llmisvc/controller_int_test.go
  pkg/testing/meta_matchers.go
Labels: approved, lgtm, llm-d

#856 fixing bug caused by misspelled BeControlledBy method
  pkg/controller/llmisvc/controller_int_test.go
Labels: approved, lgtm

#857 Add InferencePoolsReady as a subcondition to RouterReady
  pkg/apis/serving/v1alpha1/llm_inference_service_lifecycle.go
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/fixture/gwapi_builders.go
  pkg/controller/llmisvc/router.go
  pkg/controller/llmisvc/router_discovery.go
Labels: approved, lgtm

#862 Create DestinationRule with service hostname when there is no scheduler
  pkg/controller/llmisvc/workload_tls_self_signed_istio.go
Labels: approved, lgtm

#842 RHOAIENG-31916: adding support for credentials with s3 and hf storage for llmisvcs
  pkg/controller/llmisvc/config_loader.go
  pkg/controller/llmisvc/controller.go
  pkg/controller/llmisvc/controller_workload_storage_int_test.go
  pkg/controller/llmisvc/workload.go
  pkg/controller/llmisvc/workload_multi_node.go
  pkg/controller/llmisvc/workload_ocp_scc.go
  pkg/controller/llmisvc/workload_single_node.go
  pkg/controller/llmisvc/workload_storage.go
  pkg/credentials/service_account_credentials.go
  pkg/credentials/service_account_credentials_test.go
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
Labels: approved, lgtm, jira/valid-reference

#847 feat(monitoring): add monitoring resource management for LLMInferenceService
  charts/kserve-resources/templates/clusterrole.yaml
  cmd/manager/main.go
  config/monitoring/llmisvc/engine_vllm_monitor.yaml
  config/monitoring/llmisvc/kustomization.yaml
  config/monitoring/llmisvc/rbac.yaml
  config/monitoring/llmisvc/scheduler_monitor.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/controller/llmisvc/controller.go
  pkg/controller/llmisvc/controller_int_test.go
  pkg/controller/llmisvc/lifecycle_crud.go
  pkg/controller/llmisvc/monitoring.go
  pkg/testing/ctrl.go
  test/crds/monitoring_podmonitor.yaml
  test/crds/monitoring_servicemonitor.yaml
Labels: approved, lgtm

#864 Always create workload DestinationRule when router is enabled
  pkg/controller/llmisvc/workload_tls_self_signed_istio.go
Labels: approved, lgtm
